module.exports = `Commodore Nutt (April 1, 1848 – May 25, 1881) was an American entertainer. He was born George Washington Morrison Nutt in New Hampshire. He was very short. In 1861, he was touring New England with a circus when P. T. Barnum hired him to appear at the American Museum in New York City. Barnum gave Nutt the stage name Commodore Nutt, a wardrobe that included naval uniforms, and a miniature carriage in the shape of an English walnut. Nutt became one of the Museum's major attractions.

Nutt was in love with Lavinia Warren, another little person at the American Museum. Lavinia was several years older than Nutt. She thought of him only as a "nice little boy". This in some ways, made Nutt depressed later on in life. She married General Tom Thumb in a spectacular wedding masterminded by Barnum in 1863. Nutt went to the wedding as Thumb's best man. He stayed away from women for a long time after the wedding. In 1879, he married Lilian Elston of Redwood City, California.

Nutt toured the world between 1869 and 1872 with the Thumbs and Lavinia's sister, Minnie Warren. They returned to America rich after performing before royalty. Nutt left Barnum's employ after a disagreement with the showman. He toured with a comic opera company, put together a variety show on the United States West Coast, and operated saloons in Oregon and California. He returned to New York City, and died there of Bright's disease in May 1881. Nutt's career as an entertainer may have started in 1854. He may have been a performer with a small circus in Manchester. The circus manager, William C. Walker, once wrote that he discovered Nutt. He also wrote that he was the first to show him.Nutt was being exhibited and touring the New England countryside with a manager named Lillie when P. T. Barnum learned of him. Lillie was charging as little as a nickel to see the boy whose education had been neglected. Barnum was disgusted. Lillie knew nothing about exhibiting the boy "in the proper style", as Barnum put it.
Barnum met Nutt in 1861 when the boy went to the American Museum in New York City. In his autobiography, Barnum wrote that Nutt was "a most remarkable dwarf, who was a sharp, intelligent little fellow, with a deal of drollery and wit. He had a splendid head, was perfectly formed, and was very attractive, and, in short, for a 'showman' was a perfect treasure."
Barnum knew Nutt could be a major museum attraction. He hired a lawyer to lure Nutt away from his manager. Following Barnum's orders, the lawyer offered Nutt's parents a large sum of money to sign their son to a five-year contract. He promised them that the boy would be taught to be "a genteel, accomplished attractive little man".

A contract was signed on 12 December 1861. Barnum hired the 13-year-old, 29-inch George and his 21-year-old, 49-inch brother, Rodnia, Jr. The contract required Barnum to give both young men food, clothing, a place to live, and the costs of travel and medical care. Barnum promised to take care of the moral and academic education of the brothers.

Salaries would start at US$12 per week with increases every year. The two brothers would each get $30 per week in the fifth and last year of their contract. They would also get 10% from the sales of their souvenir books and photographs, with at least $240 the first year and $440 the last year. At the end of the fifth year, they would receive a carriage and a pair of ponies from Barnum. The Lightning Thief is a 2005 fantasy–adventure novel. It is based on Greek mythology. It was the first young-adult book written by author Rick Riordan. It is the first book in the Percy Jackson & the Olympians series. The series is about the adventures of modern 12-year-old Percy Jackson after he discovers he is a demigod (half-human, half-god). Percy is the son of a mortal woman and the Greek god Poseidon. Percy and his friends go on a quest (adventure) so that a war between the Greek gods Zeus, Poseidon and Hades will not happen.

Riordan finished writing his manuscript in 1994. The Lightning Thief was first bought by Bantam Books in 1997. Bantam sold it to Miramax Books. Miramax published it on June 28, 2005. The book sold more than 1.2 million copies in the next four years. The book won many awards. In 2007, it was on The New York Times Best Seller list for children's books. It was one of the Young Adult Library Services Association's Best Books for Young Adults. It was made into a movie named Percy Jackson & the Olympians: The Lightning Thief. The movie was first shown in the United States on February 12, 2010. The sequel to this book is The Sea of Monsters. Planning for both The Lightning Thief and the series began when Riordan started making up stories for his nine-year-old son, Haley. He had started studying Greek mythology (stories) in second grade. He wanted his father to tell him stories about them before he went to sleep. Riordan had a Greek mythology teacher in middle school. He remembered some of the myths, which he then told to his son. Soon, Riordan had told him all the stories. When Haley wanted him to make up new stories using the characters from the myths, Riordan created the character of Percy Jackson. Like Percy, Haley had ADHD and dyslexia. He made up the story of how Percy traveled across the United States to search for Zeus' master bolt. After hearing the story, Haley wanted his father to write a book about Percy and his friends.

In June 1994, Riordan finished the story. He started looking for agents to publish it. He went to many local colleges to find an editor before finding an agent. He gave his manuscript to his agent and editor to review. At the same time, he gave the book to some sixth, seventh and eighth graders to read and tell him what was good or bad about it. They named the book and helped Riordan describe how Percy's sword (Riptide) worked.[] In June 1997, Riordan signed with Bantam Books to prepare the book for publishing. In 2004, Miramax Books bought the book. The money was enough for Riordan to quit his teaching job and spend his time on writing. The book was published on June 28, 2005. It sold over 1.2 million copies. The book had hardcover, softcover and audio editions.]] It has been translated into many languages. It has been published all over the world. Percy Jackson is a 12 year old boy. He has ADHD and dyslexia. He has been thrown out of many schools. On a trip with his mother, he meets his friend Grover, a satyr (half-goat, half-human). Grover tells Percy's mother that Percy must go to a camp. When they drive towards the camp, a Minotaur (monster) attacks them and grabs Percy's mother. She dissolves into gold sparkles of light, but Grover and Percy escape.

Percy later wakes up. He learns that he is in Camp Half-Blood, which is a secret training camp for demigods. Percy has to live in the Hermes cabin because he does not know which god his father is. He is under the care of Luke Castellan, the cabin counselor (leader). During a game, the children of the war god Ares attack Percy. He is healed when he steps into a river. When Poseidon's trident appears above his head, Percy learns that he is Poseidon's son. After World War II, Poseidon, Hades and Zeus made an oath (promise) not to have any more children because they were too powerful. However, Poseidon broke the oath by having Percy.

Chiron tells Percy to find Zeus' master lightning bolt. Chiron thinks Hades stole the bolt. However, Zeus discovers that Poseidon has broken his oath, and thinks Poseidon told Percy to steal the bolt. He tells Percy that he has ten days until the summer solstice to find it. Before leaving, Luke gives Percy magic shoes. Percy gives them to Grover. Annabeth (a daughter of Athena) and Grover join Percy in his quest to find the bolt.

They decide to travel west to reach the entrance to the Underworld, which is in Los Angeles. They meet many Greek monsters. They also meet Ares. Ares tells Percy that his mother is alive. When they come near the pit of Tartarus, Luke’s shoes try to pull Grover into it, but he escapes. Percy meets Hades, who also thinks Percy stole the Master Bolt. He also thinks Percy stole his Helm of Darkness. Percy knows that Ares has tricked him when he finds the bolt in his backpack. He runs away from the Underworld. He has to leave his mother there. Percy fights and defeats Ares by hurting the god's heel. Ares gives Percy the Helm of Darkness. Percy gives it back to Hades. Olympus is now present at the top of the Empire State Building in New York City. Percy arrives there to give the master bolt to Zeus.

Percy goes back to camp after hearing that his mother is alive. He meets Luke, who says that he stole the bolt for Kronos. He calls a poisonous scorpion which stings and nearly kills Percy. Percy kills the scorpion first. Chiron cures Percy, who leaves camp. He goes to a new school and stays with his mother instead of staying at camp.`;
